[package]
name = "korch-slang"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "compile"
path = "src/bin/compile.rs"

[dependencies]
anyhow = "1.0"
castaway = "0.2.4"
env_logger = { version = "0.11.11", optional = true }
libloading = "0.9"
log = "0.4.33"
scopeguard = "1.2.0"
windows-core = "0.62.2"

[build-dependencies]
bindgen = "0.72.1"
